[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Prevent secrets scanning from failing the build
[secrets]
  SECRETS_SCAN_ENABLED = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 