// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkrcepveidejmaxkdhtb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrcmNlcHZlaWRlam1heGtkaHRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MjYzODcsImV4cCI6MjA2NDEwMjM4N30.ti7qMftHxhZ7niDT1f3ShZ7tHc6kA5YqXsdbFQ9uek8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);