// This file is automatically generated. Do not edit it directly.
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Export the configured client from the database config
export { supabase } from '@/config/database';